### PR TITLE
Add monotonic session for mongodb

### PR DESCRIPTION
**Pull request by alpenfritz**
## Issue

- Read from mongodb secondary

## Related Services

- amagi
- apicore
- notificator
- importer

## Implementation

- Add new singleton in amagi: `MongodbMonoSession` (use independent session from original one: `MongodbSession`)
- Set mode to `monotonic` for `MongodbMonoSession`: --> readPreference: secondaryPreferred
- Add shared functions `MonoSessionCopy` and `BeginMonoMongo` in amagi to get copies from`MongodbMonoSession`
- Add local functions in services: `apicore`, `notificator`, `importer`
- Note: not tested in local environment

## Future work

- none

### CODE REVIEW

**Comment by Hokutosei** [comment]
@alpenfritz sorry to bother,. I remember one thing. while we are in this PR, can we also set `maxPoolSize` ? to something safer less than 2000 connections? this can safely fix creo problem long term. and as well as guaranteeing our connection pool stays on the limit and reused within those limits..

thank you! 🥂

**Comment by alpenfritz** [comment]
sure, no prob

**Comment by alpenfritz** [comment]
@Hokutosei added poolLimiter

**Comment by Hokutosei** [comment]
@alpenfritz yep, already approved it 20mins ago maybe 👍very good. please release it soon

**Pull request merged**
